version: "3"

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    # volumes:
    #   - ./pgdata:/var/lib/postgresql/data

  # backend:
  #   container_name: api
  #   build:
  #     dockerfile: Dockerfile
  #     context: .
  #   restart: on-failure
  #   depends_on:
  #     - database
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - DATABASE_HOST=database
  #     - DATABASE_PORT=5432
  #     - DATABASE_USER=postgres
  #     - DATABASE_PASSWORD
  #     - DATABASE_NAME
  #     - DATABASE_SYNCHRONIZE
  #     - NODE_ENV

      # POSTGRES_USER: postgres
      # POSTGRES_DB: postgres
    # volumes:
    #   - ./pgdata:/var/lib/postgresql/data

  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: nest-docker-postgres
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - db
  #   volumes:
  #     - ./src:/app/src

  # pgadmin:
  #   image: dpage/pgadmin4
  #   restart: always
  #   container_name: nest-pgadmin4
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@admin.com
  #     - PGADMIN_DEFAULT_PASSWORD=pgadmin4
  #   ports:
  #     - '5050:80'
  #   depends_on:
  #     - db