version: "3"

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432" 
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nest-docker-postgres
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./backend/src:/app/backend/src
    environment:
      - ML_SERVICE_URL=http://ml-model:5000

  web-gui:
    build:
      context: ./web-gui
      dockerfile: Dockerfile
    container_name: web-gui
    ports:
      - '80:80'

  ml-model:
    build:
      context: ./machine-learnings
      dockerfile: Dockerfile
    volumes:
      - ./machine-learnings/model:/app/model
    depends_on:
      - db
      - app
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - db
